work_dir: experiments/hdr_former/OURHSI/inference/AdaIR

sample_path: /home/disk2/ZR/datasets/OURHSI/256/rain/storm/12_20_2_registered_raw_4773_rd_rf_or_256_512.npy
gt_path: /home/disk2/ZR/datasets/OURHSI/256/gt/12_20_2_registered_raw_4773_rd_rf_or_256_512.npy
channel_indices: [136, 67, 18]

save_name: AdaIR-OURHSI

num_bands: &num_bands 467       # 波段数

model:
  type: AdaIR
  in_channels: *num_bands
  out_channels: *num_bands
  dim: 48
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 4
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  bias: false
  LayerNorm_type: WithBias
  decoder: true

checkpoint: experiments/hdr_former/OurHSI/comparison/AdaIR/checkpoints
