work_dir: experiments/hdr_former/OURHSI/inference/SGNet

sample_path: /home/disk2/ZR/datasets/OURHSI/256/rain/storm/12_20_2_registered_raw_4773_rd_rf_or_256_512.npy
gt_path: /home/disk2/ZR/datasets/OURHSI/256/gt/12_20_2_registered_raw_4773_rd_rf_or_256_512.npy
channel_indices: [136, 67, 18]

save_name: SGNet-OURHSI

num_bands: &num_bands 467       # 波段数

model:
  type: SGNet
  in_channels: *num_bands

checkpoint: experiments/hdr_former/OURHSI/comparison/SGNet/checkpoints
